import { COLORS } from "@/src/constants/theme"
import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
  container: {
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    zIndex: 10,
    
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  backText: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.foreground,
    letterSpacing: 1,
  },
  settingsButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  settingsButtonActive: {
    backgroundColor: COLORS.primary + "30",
    borderWidth: 1,
    borderColor: COLORS.primary + "50",
  },
  settingsPanel: {
    marginHorizontal: 20,
    marginBottom: 16,
    padding: 16,
    borderRadius: 16,
    backgroundColor: "rgba(22, 61, 40, 0.95)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  settingsTabs: {
    flexDirection: "row",
    backgroundColor: "rgba(0,0,0,0.2)",
    borderRadius: 8,
    padding: 4,
    marginBottom: 16,
  },
  settingsTab: {
    flex: 1,
    paddingVertical: 8,
    alignItems: "center",
    borderRadius: 6,
  },
  settingsTabActive: {
    backgroundColor: COLORS.primary,
  },
  settingsTabText: {
    fontSize: 10,
    fontWeight: "700",
    color: "rgba(255,255,255,0.5)",
    letterSpacing: 1,
  },
  settingsTabTextActive: {
    color: COLORS.primaryForeground,
  },
  settingsLabel: {
    fontSize: 9,
    fontWeight: "700",
    color: "rgba(255,255,255,0.4)",
    letterSpacing: 1.5,
    marginBottom: 12,
  },
  themeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  themeOption: {
    width: "23%",
    alignItems: "center",
    padding: 8,
    borderRadius: 10,
  },
  themeOptionActive: {
    backgroundColor: COLORS.primary + "20",
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  colorStrip: {
    flexDirection: "row",
    width: "100%",
    height: 28,
    borderRadius: 6,
    overflow: "hidden",
  },
  colorBlock: {
    flex: 1,
  },
  themeName: {
    fontSize: 10,
    color: "rgba(255,255,255,0.6)",
    marginTop: 6,
    fontWeight: "500",
  },
  bgGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  bgOption: {
    width: "31%",
    alignItems: "center",
    padding: 8,
    borderRadius: 10,
  },
  bgOptionActive: {
    backgroundColor: COLORS.primary + "20",
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  bgPreview: {
    width: "100%",
    height: 40,
    borderRadius: 6,
  },
  titleGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  titleOption: {
    width: "48%",
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    gap: 8,
  },
  titleOptionActive: {
    backgroundColor: COLORS.primary + "20",
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  titleIconContainer: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  titleInfo: {
    flex: 1,
  },
  titleText: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.foreground,
  },
  tierBadge: {
    marginTop: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    alignSelf: "flex-start",
  },
  tierText: {
    fontSize: 8,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  checkBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  userInfo: {
    alignItems: "center",
    marginTop: 8,
  },
  userName: {
    fontSize: 20,
    fontWeight: "800",
    color: COLORS.foreground,
    letterSpacing: 0.5,
  },
  handleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  userHandle: {
    fontSize: 12,
    color: "rgba(255,255,255,0.6)",
    fontWeight: "500",
  },
  copyButton: {
    padding: 4,
  },
  identifyButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 12,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    overflow: "hidden",
  },
  identifyText: {
    fontSize: 12,
    fontWeight: "700",
  },
  avatarContainer: {
    marginTop: 24,
    marginBottom: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarGlow: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 90,
    opacity: 0.4,
    zIndex: 0,
  },
  spinningRing: {
    position: "absolute",
    zIndex: 2,
  },
  spinningRingImage: {
    width: 200,
    height: 200,
  },
  avatarFrame: {
    width: 160,
    height: 160,
    borderRadius: 80,
    padding: 6,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
  },
  avatarInner: {
    width: "100%",
    height: "100%",
    borderRadius: 74,
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "rgba(0,0,0,0.2)",
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  levelBadge: {
    position: "absolute",
    bottom: -8,
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: COLORS.background,
    zIndex: 3,
  },
  levelText: {
    fontSize: 14,
    fontWeight: "800",
    color: COLORS.background,
  },
  bannerContainer: {
    marginTop: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  bannerGlow: {
    position: "absolute",
    width: 200,
    height: 24,
    borderRadius: 12,
    opacity: 0.3,
  },
  bannerTextContainer: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
  },
  bannerText: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.foreground,
    letterSpacing: 2,
  },
  emblemContainer: {
    marginTop: 16,
  },
  statsRow: {
    flexDirection: "row",
    marginTop: 24,
    paddingHorizontal: 20,
    gap: 4,
  },
  statItem: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 8,
  },
  statIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  statValue: {
    fontSize: 14,
    fontWeight: "800",
    color: COLORS.foreground,
  },
  statLabel: {
    fontSize: 9,
    fontWeight: "600",
    color: "rgba(255,255,255,0.5)",
    letterSpacing: 1,
    textTransform: "uppercase",
    marginTop: 2,
  },
  backArrow: {
    fontSize: 22,
    color: COLORS.foreground,
    fontWeight: "300",
    lineHeight: 24,
  },
  bannerRibbon: {
    width: 288,
    height: 40,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  emblemRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  emblemLeaf: {
    fontSize: 22,
  },
  emblemDiamond: {
    width: 12,
    height: 12,
    transform: [{ rotate: "45deg" }],
  },
  checkText: {
    fontSize: 10,
    color: "#fff",
    fontWeight: "700",
  },
  sawtoothContainer: {
    flexDirection: "row",
    width: "100%",
    height: 12,
    marginTop: 20,
    overflow: "hidden",
    alignContent: "center",
  },
  sawtoothTriangle: {
    flex: 1,
    height: 0,
    borderLeftWidth: 15,
    borderRightWidth: 15,
    borderTopWidth: 12,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderTopColor: COLORS.primary + "30",
  },
})

export default styles